version: '3'

services:

  elasticsearch:

    build:
      context: ..
      dockerfile: local/elasticsearch/Dockerfile

    image: elasticsearch:local
    container_name: elasticsearch

    ports:
      - "9200:9200"


  mysql:

    build:
      context: ..
      dockerfile: local/mysql/Dockerfile

    image: mysql:local
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: TerryMysql123!@#

    ports:
      - "3306:3306"

    volumes:
      - D:/BlogData/mysql:/var/lib/mysql

  web:

    build:
      context: ..
      dockerfile: local/web/Dockerfile

    image: web:local
    container_name: web

    ports:
      - "8000:8000"

    volumes:
      - D:\Projects\PY\Blog:/home/www/Blog

    working_dir: /home/www/Blog

    command: python manage.py runserver 0:8000

    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件

    depends_on:
      - elasticsearch
      - mysql