version: '3'

services:

  web:

    build:
      context: ..
      dockerfile: local/web/Dockerfile

    image: web:local
    container_name: web

    ports:
      - "8000:8000"

    volumes:
      - D:\Projects\PY\Blog:/opt/Blog

    working_dir: /opt/Blog

    command: python manage.py runserver 0:8000

    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件